name: tests

on:
  pull_request:
    branches:
      - "15.0*"
  push:
    branches:
      - "15.0"
      - "15.0-beta"
      - "15.0-ocabot-*"

jobs:
  test:
    runs-on: ubuntu-22.04
    timeout-minutes: 40
    container: ${{ matrix.container }}
    name: ${{ matrix.name }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - container: ghcr.io/steingabelgaard/oca-ci/py3.8-odoo15.0:latest
            makepot: "true"
            name: test with Odoo
    env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
    services:
      postgres:
        image: postgres:14.0
        env:
          POSTGRES_USER: odoo
          POSTGRES_PASSWORD: odoo
          POSTGRES_DB: odoo
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Install addons and dependencies
        run: oca_install_addons ${{ github.base_ref || github.ref_name }}
      #- name: Check licenses
      #  run: manifestoo -d . check-licenses
      #- name: Check development status
      #  run: manifestoo -d . check-dev-status --default-dev-status=Beta
      - name: Initialize test db
        run: oca_init_test_database
      - name: Run tests
        run: oca_run_tests
      # - uses: codecov/codecov-action@v1
      - name: Copy .pot files
        run: sg_copy_and_commit_pot https://${{ secrets.GIT_PUSH_TOKEN }}@github.com/${{ github.repository }} 15.0-beta
        if: ${{ matrix.makepot == 'true' && github.event_name == 'push' && github.ref == 'refs/heads/15.0' && github.repository_owner == 'steingabelgaard' }}
      - name: Update .pot files
        run: oca_export_and_push_pot https://${{ secrets.GIT_PUSH_TOKEN }}@github.com/${{ github.repository }}
        if: ${{ matrix.makepot == 'true' && github.event_name == 'push' && github.ref == 'refs/heads/15.0-beta' && github.repository_owner == 'steingabelgaard' }}
